name: Deploy to Glitch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Push to Glitch
        env:
          GLITCH_TOKEN: ${{ secrets.GLITCH_TOKEN }}
        run: |
          git config --global user.email "massoumyajmal@gmail.com"
          git config --global user.name "Ajmalmassoumy"
          git remote add glitch https://${GLITCH_TOKEN}@api.glitch.com/git/boom-ludicrous-adjustment
          git push -f glitch main
